version: '3.8'

services:
    postgres:
        image: postgres
        container_name: postgres
        environment:
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test
            POSTGRES_DB: test
        ports:
            - "5432:5432"